# Generated by Django 4.2.7 on 2023-11-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="postalworker",
            name="orders_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Orders Count"),
        ),
    ]
