# Generated by Django 4.2.7 on 2023-11-28 06:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0002_postalworker_orders_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Order Title")),
                (
                    "sender_full_name",
                    models.CharField(max_length=255, verbose_name="Sender Full Name"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '09123456789'.",
                                regex="^09\\d{9}$",
                            )
                        ],
                    ),
                ),
                (
                    "sender_phone",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '09123456789'.",
                                regex="^09\\d{9}$",
                            )
                        ],
                        verbose_name="Sender Phone",
                    ),
                ),
                ("sender_address", models.TextField(verbose_name="Sender Address")),
                (
                    "receiver_full_name",
                    models.CharField(max_length=255, verbose_name="Receiver Full Name"),
                ),
                (
                    "receiver_phone",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '09123456789'.",
                                regex="^09\\d{9}$",
                            )
                        ],
                        verbose_name="Receiver Phone",
                    ),
                ),
                ("receiver_address", models.TextField(verbose_name="Receiver Address")),
                (
                    "shipment_price",
                    models.IntegerField(verbose_name="Shipment Price (Rial)"),
                ),
                ("shipment_content", models.TextField(verbose_name="Shipment Contet")),
                (
                    "shipment_size",
                    models.CharField(
                        choices=[
                            ("1", "Size 1"),
                            ("2", "Size 2"),
                            ("3", "Size 3"),
                            ("4", "Size 4"),
                            ("5", "Size 5"),
                            ("6", "Size 6"),
                            ("7", "Size 7"),
                            ("8", "Size 8"),
                            ("9", "Size 9"),
                            ("10", "Size +9"),
                        ],
                        max_length=50,
                        verbose_name="Shipment Size",
                    ),
                ),
                (
                    "shipment_count",
                    models.PositiveIntegerField(verbose_name="Shipment Count"),
                ),
                (
                    "shipment_weight",
                    models.PositiveIntegerField(verbose_name="Shipment Weight (Gram)"),
                ),
                (
                    "choosing_Service",
                    models.CharField(
                        choices=[
                            ("1", "Service 1"),
                            ("2", "Service 2"),
                            ("3", "Service 3"),
                        ],
                        max_length=50,
                        verbose_name="Choosing a Service",
                    ),
                ),
                (
                    "need_packaging",
                    models.BooleanField(
                        default=False,
                        verbose_name="Do you need an envelope/box for postage?",
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Additional Information"),
                ),
                (
                    "postal_worker",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.postalworker",
                        verbose_name="Postal Worker",
                    ),
                ),
                (
                    "sender_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User Sender",
                    ),
                ),
            ],
        ),
    ]
