# Generated by Django 4.2.7 on 2023-11-28 06:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_rename_uuid_order_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="phone_number",
        ),
        migrations.AlterField(
            model_name="order",
            name="receiver_phone",
            field=models.CharField(
                max_length=11,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '09123456789'.",
                        regex="^09\\d{9}$",
                    )
                ],
                verbose_name="Receiver Phone",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="sender_phone",
            field=models.CharField(
                max_length=11,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '09123456789'.",
                        regex="^09\\d{9}$",
                    )
                ],
                verbose_name="Sender Phone",
            ),
        ),
    ]
